// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WpfApp2;

#nullable disable

namespace WpfApp2.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20240531032135_new__migraton")]
    partial class new__migraton
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WpfApp2.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("WpfApp2.InputTable", b =>
                {
                    b.Property<int>("CityCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CityCount"));

                    b.Property<string>("CoordinatesMatrix")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisruptionPercentage")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("RouteCount")
                        .HasColumnType("integer");

                    b.HasKey("CityCount");

                    b.ToTable("InputTables");
                });

            modelBuilder.Entity("WpfApp2.ResultTable", b =>
                {
                    b.Property<int>("OptimalValue")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OptimalValue"));

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("InputTableId")
                        .HasColumnType("integer");

                    b.Property<string>("OptimalRoutes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OptimalValue");

                    b.HasIndex("InputTableId");

                    b.ToTable("ResultTables");
                });

            modelBuilder.Entity("WpfApp2.ResultTable", b =>
                {
                    b.HasOne("WpfApp2.InputTable", "InputTable")
                        .WithMany()
                        .HasForeignKey("InputTableId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InputTable");
                });
#pragma warning restore 612, 618
        }
    }
}
